features = {
    "syllabic",
    "consonantal",
    "high",
    "back",
    "low",
    "anterior",
    "coronal",
    "coronal",
    "round",
    "tense",
    "voice",
    "continuant",
    "nasal",
    "strident",
    "lateral",
}
states = {"+", "-", "0"}
phonemes = dict()
phonemes["i"] = {
    "syllabic": "+",
    "consonantal": "-",
    "high": "+",
    "back": "-",
    "low": "-",
    "anterior": "-",
    "coronal": "-",
    "round": "-",
    "tense": "+",
    "voice": "0",
    "continuant": "0",
    "nasal": "0",
    "strident": "0",
    "lateral": "0",
}
phonemes["u"] = {
    "syllabic": "+",
    "consonantal": "-",
    "high": "+",
    "back": "+",
    "low": "-",
    "anterior": "-",
    "coronal": "-",
    "round": "+",
    "tense": "+",
    "voice": "0",
    "continuant": "0",
    "nasal": "0",
    "strident": "0",
    "lateral": "0",
}
phonemes["e"] = {
    "syllabic": "+",
    "consonantal": "-",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "-",
    "coronal": "-",
    "round": "-",
    "tense": "+",
    "voice": "0",
    "continuant": "0",
    "nasal": "0",
    "strident": "0",
    "lateral": "0",
}
phonemes["ɑ"] = {
    "syllabic": "+",
    "consonantal": "-",
    "high": "-",
    "back": "+",
    "low": "+",
    "anterior": "-",
    "coronal": "-",
    "round": "-",
    "tense": "+",
    "voice": "0",
    "continuant": "0",
    "nasal": "0",
    "strident": "0",
    "lateral": "0",
}
phonemes["ɪ"] = {
    "syllabic": "+",
    "consonantal": "-",
    "high": "+",
    "back": "-",
    "low": "-",
    "anterior": "-",
    "coronal": "-",
    "round": "-",
    "tense": "-",
    "voice": "0",
    "continuant": "0",
    "nasal": "0",
    "strident": "0",
    "lateral": "0",
}
phonemes["w"] = {
    "syllabic": "-",
    "consonantal": "-",
    "high": "+",
    "back": "+",
    "low": "-",
    "anterior": "-",
    "coronal": "-",
    "round": "+",
    "tense": "-",
    "voice": "0",
    "continuant": "0",
    "nasal": "0",
    "strident": "0",
    "lateral": "0",
}
phonemes["r"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "-",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "+",
    "continuant": "+",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
phonemes["l"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "+",
    "continuant": "+",
    "nasal": "-",
    "strident": "-",
    "lateral": "+",
}
phonemes["p"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "-",
    "round": "0",
    "tense": "0",
    "voice": "-",
    "continuant": "-",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
phonemes["b"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "-",
    "round": "0",
    "tense": "0",
    "voice": "+",
    "continuant": "-",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
phonemes["t"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "-",
    "continuant": "-",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
phonemes["d"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "+",
    "continuant": "-",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
phonemes["θ"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "-",
    "continuant": "+",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
phonemes["ð"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "+",
    "continuant": "+",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
phonemes["n"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "+",
    "continuant": "-",
    "nasal": "+",
    "strident": "-",
    "lateral": "-",
}
phonemes["s"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "-",
    "continuant": "+",
    "nasal": "-",
    "strident": "+",
    "lateral": "-",
}
phonemes["z"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "-",
    "back": "-",
    "low": "-",
    "anterior": "+",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "+",
    "continuant": "+",
    "nasal": "-",
    "strident": "+",
    "lateral": "-",
}
phonemes["ʃ"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "+",
    "back": "-",
    "low": "-",
    "anterior": "-",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "-",
    "continuant": "+",
    "nasal": "-",
    "strident": "+",
    "lateral": "-",
}
phonemes["ʒ"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "+",
    "back": "-",
    "low": "-",
    "anterior": "-",
    "coronal": "+",
    "round": "0",
    "tense": "0",
    "voice": "+",
    "continuant": "+",
    "nasal": "-",
    "strident": "+",
    "lateral": "-",
}
phonemes["k"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "+",
    "back": "+",
    "low": "-",
    "anterior": "-",
    "coronal": "-",
    "round": "0",
    "tense": "0",
    "voice": "-",
    "continuant": "-",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
phonemes["g"] = {
    "syllabic": "-",
    "consonantal": "+",
    "high": "+",
    "back": "+",
    "low": "-",
    "anterior": "-",
    "coronal": "-",
    "round": "0",
    "tense": "0",
    "voice": "-",
    "continuant": "-",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
phonemes["h"] = {
    "syllabic": "-",
    "consonantal": "-",
    "high": "-",
    "back": "-",
    "low": "+",
    "anterior": "-",
    "coronal": "-",
    "round": "0",
    "tense": "0",
    "voice": "-",
    "continuant": "+",
    "nasal": "-",
    "strident": "-",
    "lateral": "-",
}
print(phonemes)
